### ISSUE TITLE
No fleet on balena hub

### ISSUE THREAD

**Issue by uros76** [NebraLtd/helium-rak#20] opened 2023-02-07 16:05 UTC
Hi. Did something happen with Rak fleet? It's not on balena hub anymore 😒
This link [nebra.io/rak](https://nebra.io/rak) gives me an `error: failed to fetch resource`

**Comment by shawaj** [comment] 2023-02-07 20:41
Duplicate of https://github.com/NebraLtd/helium-miner-software/issues/608

**Closed as completed by shawaj** 2023-02-07 20:41 UTC

**Comment by shawaj** [comment] 2023-02-07 20:42
Duplicate of #18
